### ISSUE TITLE
Feature: User can 

### ISSUE THREAD

**Issue by NoahLett** [NoahLett/portfolio#1]
## ⚙️ Feature

User can view a landing page that provides a brief description of my skill set, along with a navbar at the top. 

## 📐 Functionality

The user can quickly learn more about my skill set by reading the brief description, or they can use the navbar to change pages to a "skills", "projects", or "connect" page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Ensure that all necessary dependencies and scripts have been added to package.json
- [ ] Develop the basic layout of app.jsx by using a function component 
- [ ] Set up the render of App in index.js
- [ ] Implant the root into the HTML file
- [ ] Create a home.jsx page 
- [ ] Use a functional component to render the data that will be showed on the home page
- [ ] Use flexbox to correctly lay out the elements being rendered by the home.jsx component
- [ ] Use bootstrap 5.3 for aesthetic touches 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
